### ISSUE TITLE
v2-websocket always failed with status code 429

### ISSUE THREAD

**Issue by mcsrainbow** [aws-samples/aws-serverless-openai-chatbot-demo#20]
Any input returned same error messages as below:
```
Request failed with status code 429|Error: Request failed with status code 429
at createError (/var/task/node_modules/axios/lib/core/createError.js:16:15)
at settle (/var/task/node_modules/axios/lib/core/settle.js:17:12)
at IncomingMessage.handleStreamEnd (/var/task/node_modules/axios/lib/adapters/http.js:322:11)
at IncomingMessage.emit (node:events:525:35)
at endReadableNT (node:internal/streams/readable:1359:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by mcsrainbow** [comment]
Close this issue as it's due to [Error Code 429 - You exceeded your current quota, please check your plan and billing details.](https://help.openai.com/en/articles/6891831-error-code-429-you-exceeded-your-current-quota-please-check-your-plan-and-billing-details#:~:text=This%20error%20message%20indicates%20that,limit%20of%20your%20billing%20cycle)
