### ISSUE TITLE
V2版本部署后登录提示401

### ISSUE THREAD

**Issue by hill007** [aws-samples/aws-serverless-openai-chatbot-demo#21]
你好，
      按照V2.0版本部署上去后提示401，请问是哪里有问题吗？
![图片](https://user-images.githubusercontent.com/54256063/221855704-77ae3db6-9fa9-4ce3-9075-af801e880785.png)
lamada如下：
![图片](https://user-images.githubusercontent.com/54256063/221855974-d47d3626-6e69-44c3-a5cc-d546101a5b6d.png)

**Comment by ciscogeek** [comment]
apigw里的url是不是正确？看看处理登录的lambda的日志里有什么报错？

**Comment by xiehust** [comment]
是滴， login的url应该是访问的http Gateway的endpint URL+/login， 先检查下

**Comment by sunraysir** [comment]
我剛裝完, 都是一樣的問題

**Comment by sunraysir** [comment]
2024-07-30T10:34:56.693Z
2024-07-30T10:34:56.693Z	undefined	ERROR	Uncaught Exception 	
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'index'\nRequire stack:\n- /var/runtime/index.mjs",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'index'",
        "Require stack:",
        "- /var/runtime/index.mjs",
        "    at _loadUserApp (file:///var/runtime/index.mjs:1087:17)",
        "    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1119:21)",
        "    at async start (file:///var/runtime/index.mjs:1282:23)",
        "    at async file:///var/runtime/index.mjs:1288:1"
    ]
}

**Comment by sunraysir** [comment]
// const DEFAULT_REGION = "ap-northeast-1";
const TABLE_NAME = "chat_user_info";

how to change the region?

**Comment by sunraysir** [comment]
Ops! Error: 500,{"message":"Request failed with status code 404","name":"Error","stack":"Error: Request failed with status code 404\n at createError (/var/task/node_modules/axios/lib/core/createError.js:16:15)\n at settle (/var/task/node_modules/axios/lib/core/settle.js:17:12)\n at IncomingMessage.handleStreamEnd (/var/task/node_modules/axios/lib/adapters/http.js:322:11)\n at IncomingMessage.emit (node:events:529:35)\n at endReadableNT (node:internal/streams/readable:1400:12)\n at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","User-Agent":"OpenAI/NodeJS/3.1.0","Authorization":"Bearer sk-None-iv8jFB8BdlAW9uDt8kcdT3BlbkFJKULXVKenOfgyy6q97KCR","Content-Length":137},"method":"post","data":"{\"model\":\"code-davinci-002\",\"prompt\":\"\\nhi\\n\",\"temperature\":0,\"max_tokens\":2000,\"top_p\":1,\"frequency_penalty\":0.5,\"presence_penalty\":0.1}","url":"https://api.openai.com/v1/completions"},"status":404}

**Comment by sunraysir** [comment]
2024-07-31T06:15:03.879Z	3436db63-048e-4e07-b2d6-6602c1fc1004	ERROR	Invoke Error 	{
    "errorType": "SyntaxError",
    "errorMessage": "Unexpected token u in JSON at position 0",
    "stack": [
        "SyntaxError: Unexpected token u in JSON at position 0",
        "    at JSON.parse (<anonymous>)",
        "    at Runtime.handler (file:///var/task/index.mjs:12:21)",
        "    at Runtime.handleOnceNonStreaming (file:///var/runtime/index.mjs:1173:29)"
    ]
}

**Comment by sunraysir** [comment]
2024-07-31T06:46:09.839Z	d1b609c0-35ea-4e37-8668-f1eeffaba0ef	ERROR	Invoke Error 	{
    "errorType": "TypeError",
    "errorMessage": "Cannot read properties of undefined (reading 'authorization')",
    "stack": [
        "TypeError: Cannot read properties of undefined (reading 'authorization')",
        "    at Runtime.handler (file:///var/task/index.mjs:16:32)",
        "    at Runtime.handleOnceNonStreaming (file:///var/runtime/index.mjs:1173:29)"
    ]
}
