### ISSUE TITLE
v2-websocket deployment: Unrecognized resource types: [AWS::Lambda::Url]

### ISSUE THREAD

**Issue by dxxzdxxz** [aws-samples/aws-serverless-openai-chatbot-demo#26]
When deploy v2-websocket in AWS China, it raises error deploying the websocket-api-gateway-chat stack.

```
OpenAIChatBotWsApiGwChatStack-test: creating CloudFormation changeset...

 ❌  websocket-api-gateway-chat (OpenAIChatBotWsApiGwChatStack-test) failed: Error [ValidationError]: Template format error: Unrecognized resource types: [AWS::Lambda::Url]
    at Request.extractError (/usr/local/lib/node_modules/aws-cdk/lib/index.js:254:46127)
    at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/lib/index.js:254:88989)
    at Request.emit (/usr/local/lib/node_modules/aws-cdk/lib/index.js:254:88437)
    at Request.emit (/usr/local/lib/node_modules/aws-cdk/lib/index.js:254:194844)
    at Request.transition (/usr/local/lib/node_modules/aws-cdk/lib/index.js:254:188396)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/aws-cdk/lib/index.js:254:153268)
    at /usr/local/lib/node_modules/aws-cdk/lib/index.js:254:153598
    at Request.<anonymous> (/usr/local/lib/node_modules/aws-cdk/lib/index.js:254:188688)
    at Request.<anonymous> (/usr/local/lib/node_modules/aws-cdk/lib/index.js:254:194919)
    at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/lib/index.js:254:89157) {
  code: 'ValidationError',
  time: 2023-03-08T03:04:25.241Z,
  requestId: '43205935-2295-4757-9d42-4a018ce5178f',
  statusCode: 400,
  retryable: false,
  retryDelay: 516.2804870621469
}

 ❌ Deployment failed: Error: Stack Deployments Failed: ValidationError: Template format error: Unrecognized resource types: [AWS::Lambda::Url]
    at deployStacks (/usr/local/lib/node_modules/aws-cdk/lib/index.js:362:129094)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async CdkToolkit.deploy (/usr/local/lib/node_modules/aws-cdk/lib/index.js:362:146822)
    at async exec4 (/usr/local/lib/node_modules/aws-cdk/lib/index.js:417:51795)

Stack Deployments Failed: ValidationError: Template format error: Unrecognized resource types: [AWS::Lambda::Url]
```

OS: macOS Ventura 13.2.1 (Intel)
cdk: 2.67.0 (build b6f7f39)
go: go1.19.6 darwin/amd64
node: v16.19.1 (nodejs 18.x not support in AWS China Lambda)

**Comment by xiehust** [comment]
All I did is in the regions out side of CN. Btw I heard OpenAI restricts the API access from CN and HK, so I suggest you deploy it in other regions except CN and HK.
